"""站点配置文件 — 25个实测可用站点"""
SITE_PROFILES = {
    "163news":{"name":"网易新闻","domain":"www.163.com","category":"news","rss_feeds":[],"sitemap_urls":["https://www.163.com/sitemap.xml"],"archive_urls":[],"start_urls":["https://www.163.com/"],"article_link_pattern":"/\\d{2}/\\d{4}/\\d{2}/[A-Z0-9]+\\.html","title_selector":".post_title::text, h1::text, title::text","body_selector":".post_body, .article-content, article","date_selector":".post_info::text, .time::text"},
    "36kr":{"name":"36氪","domain":"36kr.com","category":"news","rss_feeds":["https://36kr.com/feed"],"sitemap_urls":["https://36kr.com/sitemap.xml"],"archive_urls":[],"start_urls":["https://36kr.com/"],"article_link_pattern":"/p/\\d+","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .article-detail, article","date_selector":".article-date::text, time::attr(datetime)"},
    "autohome":{"name":"汽车之家","domain":"www.autohome.com.cn","category":"review","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.autohome.com.cn/news/1/"],"article_link_pattern":"/news/\\d{6}/\\d+\\.html","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text"},
    "cnblogs":{"name":"博客园","domain":"www.cnblogs.com","category":"blog","rss_feeds":["https://feed.cnblogs.com/blog/sitehome/rss"],"sitemap_urls":["https://www.cnblogs.com/sitemap.xml"],"archive_urls":[],"start_urls":["https://www.cnblogs.com/"],"article_link_pattern":"/[a-zA-Z0-9_\\-]+/p/\\d+","title_selector":"#cb_post_title_url::text, h1::text, title::text","body_selector":"#cnblogs_post_body, .postBody, article","date_selector":"#post-date::text, .postDesc::text"},
    "csdn":{"name":"CSDN","domain":"blog.csdn.net","category":"blog","rss_feeds":["https://blog.csdn.net/nav/ai/rss"],"sitemap_urls":["https://blog.csdn.net/sitemap.xml"],"archive_urls":[],"start_urls":["https://blog.csdn.net/"],"article_link_pattern":"/[a-zA-Z0-9_\\-]+/article/details/\\d+","title_selector":".title-article::text, h1::text, title::text","body_selector":"#content_views, #article_content, article","date_selector":".time::text, .postTime::text"},
    "douban":{"name":"豆瓣","domain":"www.douban.com","category":"social","rss_feeds":[],"sitemap_urls":["https://www.douban.com/sitemap.xml"],"archive_urls":[],"start_urls":["https://www.douban.com/"],"article_link_pattern":"/(review|note)/\\d+","title_selector":"h1::text, .title::text, title::text","body_selector":".review-content, .note-content, article","date_selector":".pub-date::text, .time::text"},
    "gamersky":{"name":"游民星空","domain":"www.gamersky.com","category":"review","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.gamersky.com/news/"],"article_link_pattern":"/news/\\d{6}/\\d+\\.html","title_selector":".title::text, h1::text, title::text","body_selector":".Mid2L_con, .article-content, article","date_selector":".time::text, .date::text"},
    "guokr":{"name":"果壳","domain":"www.guokr.com","category":"blog","rss_feeds":["https://www.guokr.com/rss/"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.guokr.com/"],"article_link_pattern":"/article/\\d+","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text, .date::text"},
    "hupu":{"name":"虎扑","domain":"bbs.hupu.com","category":"social","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://bbs.hupu.com/bxj-1"],"article_link_pattern":"/\\d+\\.html","title_selector":".title::text, h1::text, title::text","body_selector":".post-content, .topic-content, article","date_selector":".post-time::text, .time::text"},
    "huxiu":{"name":"虎嗅","domain":"www.huxiu.com","category":"news","rss_feeds":["https://www.huxiu.com/rss/0.xml"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.huxiu.com/"],"article_link_pattern":"/article/\\d+\\.html","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .article-body, article","date_selector":".article-date::text, .time::text"},
    "ifanr":{"name":"爱范儿","domain":"www.ifanr.com","category":"news","rss_feeds":["https://www.ifanr.com/feed"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.ifanr.com/"],"article_link_pattern":"/\\d+","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text, .date::text"},
    "ithome":{"name":"IT之家","domain":"www.ithome.com","category":"news","rss_feeds":["https://www.ithome.com/rss/"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.ithome.com/"],"article_link_pattern":"/\\d+/\\d+\\.htm","title_selector":".post_title::text, h1::text, title::text","body_selector":".post_content, .article-content, article","date_selector":".post_time::text, .time::text"},
    "jianshu":{"name":"简书","domain":"www.jianshu.com","category":"social","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.jianshu.com/"],"article_link_pattern":"/p/[a-f0-9]+","title_selector":"h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".publish-time::text, .time::text"},
    "jiqizhixin":{"name":"机器之心","domain":"www.jiqizhixin.com","category":"blog","rss_feeds":["https://www.jiqizhixin.com/rss"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.jiqizhixin.com/"],"article_link_pattern":"/articles/\\d{4}-\\d{2}-\\d{2}-\\d+","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text, .date::text"},
    "people":{"name":"人民网","domain":"www.people.com.cn","category":"news","rss_feeds":[],"sitemap_urls":["http://www.people.com.cn/sitemap.xml"],"archive_urls":[],"start_urls":["http://www.people.com.cn/"],"article_link_pattern":"/n1/\\d{4}/\\d{4}/c\\d+-\\d+\\.html","title_selector":".text_title::text, h1::text, title::text","body_selector":".show_text, .text_con, article","date_selector":".box01 .fl::text, .pub_time::text"},
    "qqnews":{"name":"腾讯新闻","domain":"news.qq.com","category":"news","rss_feeds":[],"sitemap_urls":["https://news.qq.com/sitemap.xml"],"archive_urls":[],"start_urls":["https://news.qq.com/"],"article_link_pattern":"/rain/a/\\d+|/omn/\\d+","title_selector":".title::text, h1::text, title::text","body_selector":".content-article, .article-content, article","date_selector":".date::text, .time::text"},
    "sina":{"name":"新浪新闻","domain":"news.sina.com.cn","category":"news","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://news.sina.com.cn/"],"article_link_pattern":"/doc-[a-z0-9]+\\.html","title_selector":".main-title::text, h1::text, title::text","body_selector":".article, #article, .article-content, article","date_selector":".date::text, .time-source::text"},
    "smzdm":{"name":"什么值得买","domain":"www.smzdm.com","category":"review","rss_feeds":["https://feed.smzdm.com/"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.smzdm.com/"],"article_link_pattern":"/p/\\d+","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text, .date::text"},
    "sohu":{"name":"搜狐","domain":"www.sohu.com","category":"news","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.sohu.com/c/8/1460"],"article_link_pattern":"/a/\\d+_\\d+","title_selector":".text-title h1::text, h1::text, title::text","body_selector":".article, .text-content, article","date_selector":".time::text, .article-time::text"},
    "tmtpost":{"name":"钛媒体","domain":"www.tmtpost.com","category":"news","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.tmtpost.com/"],"article_link_pattern":"/\\d+\\.html","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .post-content, article","date_selector":".time::text, .date::text"},
    "v2ex":{"name":"V2EX","domain":"www.v2ex.com","category":"social","rss_feeds":["https://www.v2ex.com/feed/tab/hot.xml"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.v2ex.com/"],"article_link_pattern":"/t/\\d+","title_selector":"h1::text, title::text","body_selector":".topic_content, .markdown_body, article","date_selector":".header small.gray::text"},
    "woshipm":{"name":"人人都是PM","domain":"www.woshipm.com","category":"blog","rss_feeds":["https://www.woshipm.com/feed"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.woshipm.com/category/pmd"],"article_link_pattern":"/\\w+/\\d+\\.html","title_selector":".article-title::text, h1::text, title::text","body_selector":".article-content, .content, article","date_selector":".time::text, .date::text"},
    "xinhua":{"name":"新华网","domain":"www.news.cn","category":"news","rss_feeds":[],"sitemap_urls":["https://www.news.cn/sitemap.xml"],"archive_urls":[],"start_urls":["https://www.news.cn/"],"article_link_pattern":"/\\d{4}-\\d{2}/\\d{2}/c_\\d+\\.htm","title_selector":".title::text, h1::text, title::text","body_selector":".article-content, #detailContent, article","date_selector":".date::text, .time::text"},
    "yicai":{"name":"第一财经","domain":"www.yicai.com","category":"news","rss_feeds":["https://www.yicai.com/feed"],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.yicai.com/news/"],"article_link_pattern":"/news/\\d+\\.html","title_selector":".title::text, h1::text, title::text","body_selector":".m-text, .article-content, article","date_selector":".time::text, .date::text"},
    "zhihu":{"name":"知乎","domain":"www.zhihu.com","category":"social","rss_feeds":[],"sitemap_urls":[],"archive_urls":[],"start_urls":["https://www.zhihu.com/explore"],"article_link_pattern":"/p/\\d+","title_selector":".Post-Title::text, h1::text, title::text","body_selector":".Post-RichText, .RichText, article","date_selector":".Post-Time::text, time::attr(datetime)"},
}

SITE_LIST = sorted(SITE_PROFILES.keys())
DEFAULT_PER_SITE_LIMIT = 20000
